# 1. make sure state bucket is created

# 2. Create deployment bucket
#    - compile lambda js to zip
#    - upload the zip to deployment bucket

# 3. provision lambda

# 4. provision API gateway for the REST API
